### YamlMime:ManagedReference
items:
- uid: MoraGames.MapGen.AdvancedSettings
  commentId: T:MoraGames.MapGen.AdvancedSettings
  id: AdvancedSettings
  parent: MoraGames.MapGen
  children:
  - MoraGames.MapGen.AdvancedSettings.#ctor
  - MoraGames.MapGen.AdvancedSettings.CorridorPixelColor
  - MoraGames.MapGen.AdvancedSettings.CorridorWeight
  - MoraGames.MapGen.AdvancedSettings.DeadEndWeight
  - MoraGames.MapGen.AdvancedSettings.RoomPixelColor
  - MoraGames.MapGen.AdvancedSettings.RoomWeight
  - MoraGames.MapGen.AdvancedSettings.SpriteTemplatesPath
  - MoraGames.MapGen.AdvancedSettings.WallPixelColor
  langs:
  - csharp
  - vb
  name: AdvancedSettings
  nameWithType: AdvancedSettings
  fullName: MoraGames.MapGen.AdvancedSettings
  type: Class
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen
  syntax:
    content: public class AdvancedSettings
    content.vb: Public Class AdvancedSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: MoraGames.MapGen.AdvancedSettings.SpriteTemplatesPath
  commentId: F:MoraGames.MapGen.AdvancedSettings.SpriteTemplatesPath
  id: SpriteTemplatesPath
  parent: MoraGames.MapGen.AdvancedSettings
  langs:
  - csharp
  - vb
  name: SpriteTemplatesPath
  nameWithType: AdvancedSettings.SpriteTemplatesPath
  fullName: MoraGames.MapGen.AdvancedSettings.SpriteTemplatesPath
  type: Field
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen
  syntax:
    content: public string SpriteTemplatesPath
    return:
      type: System.String
    content.vb: Public SpriteTemplatesPath As String
- uid: MoraGames.MapGen.AdvancedSettings.RoomWeight
  commentId: F:MoraGames.MapGen.AdvancedSettings.RoomWeight
  id: RoomWeight
  parent: MoraGames.MapGen.AdvancedSettings
  langs:
  - csharp
  - vb
  name: RoomWeight
  nameWithType: AdvancedSettings.RoomWeight
  fullName: MoraGames.MapGen.AdvancedSettings.RoomWeight
  type: Field
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen
  syntax:
    content: public float RoomWeight
    return:
      type: System.Single
    content.vb: Public RoomWeight As Single
- uid: MoraGames.MapGen.AdvancedSettings.CorridorWeight
  commentId: F:MoraGames.MapGen.AdvancedSettings.CorridorWeight
  id: CorridorWeight
  parent: MoraGames.MapGen.AdvancedSettings
  langs:
  - csharp
  - vb
  name: CorridorWeight
  nameWithType: AdvancedSettings.CorridorWeight
  fullName: MoraGames.MapGen.AdvancedSettings.CorridorWeight
  type: Field
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen
  syntax:
    content: public float CorridorWeight
    return:
      type: System.Single
    content.vb: Public CorridorWeight As Single
- uid: MoraGames.MapGen.AdvancedSettings.DeadEndWeight
  commentId: F:MoraGames.MapGen.AdvancedSettings.DeadEndWeight
  id: DeadEndWeight
  parent: MoraGames.MapGen.AdvancedSettings
  langs:
  - csharp
  - vb
  name: DeadEndWeight
  nameWithType: AdvancedSettings.DeadEndWeight
  fullName: MoraGames.MapGen.AdvancedSettings.DeadEndWeight
  type: Field
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen
  syntax:
    content: public float DeadEndWeight
    return:
      type: System.Single
    content.vb: Public DeadEndWeight As Single
- uid: MoraGames.MapGen.AdvancedSettings.CorridorPixelColor
  commentId: F:MoraGames.MapGen.AdvancedSettings.CorridorPixelColor
  id: CorridorPixelColor
  parent: MoraGames.MapGen.AdvancedSettings
  langs:
  - csharp
  - vb
  name: CorridorPixelColor
  nameWithType: AdvancedSettings.CorridorPixelColor
  fullName: MoraGames.MapGen.AdvancedSettings.CorridorPixelColor
  type: Field
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen
  syntax:
    content: public Color CorridorPixelColor
    return:
      type: UnityEngine.Color
    content.vb: Public CorridorPixelColor As Color
- uid: MoraGames.MapGen.AdvancedSettings.RoomPixelColor
  commentId: F:MoraGames.MapGen.AdvancedSettings.RoomPixelColor
  id: RoomPixelColor
  parent: MoraGames.MapGen.AdvancedSettings
  langs:
  - csharp
  - vb
  name: RoomPixelColor
  nameWithType: AdvancedSettings.RoomPixelColor
  fullName: MoraGames.MapGen.AdvancedSettings.RoomPixelColor
  type: Field
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen
  syntax:
    content: public Color RoomPixelColor
    return:
      type: UnityEngine.Color
    content.vb: Public RoomPixelColor As Color
- uid: MoraGames.MapGen.AdvancedSettings.WallPixelColor
  commentId: F:MoraGames.MapGen.AdvancedSettings.WallPixelColor
  id: WallPixelColor
  parent: MoraGames.MapGen.AdvancedSettings
  langs:
  - csharp
  - vb
  name: WallPixelColor
  nameWithType: AdvancedSettings.WallPixelColor
  fullName: MoraGames.MapGen.AdvancedSettings.WallPixelColor
  type: Field
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen
  syntax:
    content: public Color WallPixelColor
    return:
      type: UnityEngine.Color
    content.vb: Public WallPixelColor As Color
- uid: MoraGames.MapGen.AdvancedSettings.#ctor
  commentId: M:MoraGames.MapGen.AdvancedSettings.#ctor
  id: '#ctor'
  parent: MoraGames.MapGen.AdvancedSettings
  langs:
  - csharp
  - vb
  name: AdvancedSettings()
  nameWithType: AdvancedSettings.AdvancedSettings()
  fullName: MoraGames.MapGen.AdvancedSettings.AdvancedSettings()
  type: Constructor
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen
  syntax:
    content: public AdvancedSettings()
    content.vb: Public Sub New()
  overload: MoraGames.MapGen.AdvancedSettings.#ctor*
  nameWithType.vb: AdvancedSettings.New()
  fullName.vb: MoraGames.MapGen.AdvancedSettings.New()
  name.vb: New()
references:
- uid: MoraGames.MapGen
  commentId: N:MoraGames.MapGen
  isExternal: true
  href: MoraGames.html
  name: MoraGames.MapGen
  nameWithType: MoraGames.MapGen
  fullName: MoraGames.MapGen
  spec.csharp:
  - uid: MoraGames
    name: MoraGames
    isExternal: true
    href: MoraGames.html
  - name: .
  - uid: MoraGames.MapGen
    name: MapGen
    isExternal: true
    href: MoraGames.MapGen.html
  spec.vb:
  - uid: MoraGames
    name: MoraGames
    isExternal: true
    href: MoraGames.html
  - name: .
  - uid: MoraGames.MapGen
    name: MapGen
    isExternal: true
    href: MoraGames.MapGen.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: UnityEngine.Color
  isExternal: true
  name: Color
  nameWithType: Color
  fullName: UnityEngine.Color
- uid: MoraGames.MapGen.AdvancedSettings.#ctor*
  commentId: Overload:MoraGames.MapGen.AdvancedSettings.#ctor
  isExternal: true
  href: MoraGames.MapGen.AdvancedSettings.html#MoraGames_MapGen_AdvancedSettings__ctor
  name: AdvancedSettings
  nameWithType: AdvancedSettings.AdvancedSettings
  fullName: MoraGames.MapGen.AdvancedSettings.AdvancedSettings
  nameWithType.vb: AdvancedSettings.New
  fullName.vb: MoraGames.MapGen.AdvancedSettings.New
  name.vb: New
