### YamlMime:ManagedReference
items:
- uid: MoraGames.MapGen.MapGenSettingsSOEditor
  commentId: T:MoraGames.MapGen.MapGenSettingsSOEditor
  id: MapGenSettingsSOEditor
  parent: MoraGames.MapGen
  children:
  - MoraGames.MapGen.MapGenSettingsSOEditor.#ctor
  - MoraGames.MapGen.MapGenSettingsSOEditor.OnInspectorGUI
  langs:
  - csharp
  - vb
  name: MapGenSettingsSOEditor
  nameWithType: MapGenSettingsSOEditor
  fullName: MoraGames.MapGen.MapGenSettingsSOEditor
  type: Class
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen
  syntax:
    content: 'public class MapGenSettingsSOEditor : Editor'
    content.vb: Public Class MapGenSettingsSOEditor Inherits Editor
  inheritance:
  - System.Object
- uid: MoraGames.MapGen.MapGenSettingsSOEditor.OnInspectorGUI
  commentId: M:MoraGames.MapGen.MapGenSettingsSOEditor.OnInspectorGUI
  id: OnInspectorGUI
  parent: MoraGames.MapGen.MapGenSettingsSOEditor
  langs:
  - csharp
  - vb
  name: OnInspectorGUI()
  nameWithType: MapGenSettingsSOEditor.OnInspectorGUI()
  fullName: MoraGames.MapGen.MapGenSettingsSOEditor.OnInspectorGUI()
  type: Method
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen
  example: []
  syntax:
    content: public override void OnInspectorGUI()
    content.vb: Public Overrides Sub OnInspectorGUI()
  overload: MoraGames.MapGen.MapGenSettingsSOEditor.OnInspectorGUI*
- uid: MoraGames.MapGen.MapGenSettingsSOEditor.#ctor
  commentId: M:MoraGames.MapGen.MapGenSettingsSOEditor.#ctor
  id: '#ctor'
  parent: MoraGames.MapGen.MapGenSettingsSOEditor
  langs:
  - csharp
  - vb
  name: MapGenSettingsSOEditor()
  nameWithType: MapGenSettingsSOEditor.MapGenSettingsSOEditor()
  fullName: MoraGames.MapGen.MapGenSettingsSOEditor.MapGenSettingsSOEditor()
  type: Constructor
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen
  syntax:
    content: public MapGenSettingsSOEditor()
    content.vb: Public Sub New()
  overload: MoraGames.MapGen.MapGenSettingsSOEditor.#ctor*
  nameWithType.vb: MapGenSettingsSOEditor.New()
  fullName.vb: MoraGames.MapGen.MapGenSettingsSOEditor.New()
  name.vb: New()
references:
- uid: MoraGames.MapGen
  commentId: N:MoraGames.MapGen
  isExternal: true
  href: MoraGames.html
  name: MoraGames.MapGen
  nameWithType: MoraGames.MapGen
  fullName: MoraGames.MapGen
  spec.csharp:
  - uid: MoraGames
    name: MoraGames
    isExternal: true
    href: MoraGames.html
  - name: .
  - uid: MoraGames.MapGen
    name: MapGen
    isExternal: true
    href: MoraGames.MapGen.html
  spec.vb:
  - uid: MoraGames
    name: MoraGames
    isExternal: true
    href: MoraGames.html
  - name: .
  - uid: MoraGames.MapGen
    name: MapGen
    isExternal: true
    href: MoraGames.MapGen.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MoraGames.MapGen.MapGenSettingsSOEditor.OnInspectorGUI*
  commentId: Overload:MoraGames.MapGen.MapGenSettingsSOEditor.OnInspectorGUI
  isExternal: true
  href: MoraGames.MapGen.MapGenSettingsSOEditor.html#MoraGames_MapGen_MapGenSettingsSOEditor_OnInspectorGUI
  name: OnInspectorGUI
  nameWithType: MapGenSettingsSOEditor.OnInspectorGUI
  fullName: MoraGames.MapGen.MapGenSettingsSOEditor.OnInspectorGUI
- uid: MoraGames.MapGen.MapGenSettingsSOEditor.#ctor*
  commentId: Overload:MoraGames.MapGen.MapGenSettingsSOEditor.#ctor
  isExternal: true
  href: MoraGames.MapGen.MapGenSettingsSOEditor.html#MoraGames_MapGen_MapGenSettingsSOEditor__ctor
  name: MapGenSettingsSOEditor
  nameWithType: MapGenSettingsSOEditor.MapGenSettingsSOEditor
  fullName: MoraGames.MapGen.MapGenSettingsSOEditor.MapGenSettingsSOEditor
  nameWithType.vb: MapGenSettingsSOEditor.New
  fullName.vb: MoraGames.MapGen.MapGenSettingsSOEditor.New
  name.vb: New
