### YamlMime:ManagedReference
items:
- uid: MoraGames.MapGen.Props.PropRotationSettingsEditor
  commentId: T:MoraGames.MapGen.Props.PropRotationSettingsEditor
  id: PropRotationSettingsEditor
  parent: MoraGames.MapGen.Props
  children:
  - MoraGames.MapGen.Props.PropRotationSettingsEditor.#ctor
  - MoraGames.MapGen.Props.PropRotationSettingsEditor.OnInspectorGUI
  langs:
  - csharp
  - vb
  name: PropRotationSettingsEditor
  nameWithType: PropRotationSettingsEditor
  fullName: MoraGames.MapGen.Props.PropRotationSettingsEditor
  type: Class
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen.Props
  syntax:
    content: 'public class PropRotationSettingsEditor : Editor'
    content.vb: Public Class PropRotationSettingsEditor Inherits Editor
  inheritance:
  - System.Object
- uid: MoraGames.MapGen.Props.PropRotationSettingsEditor.OnInspectorGUI
  commentId: M:MoraGames.MapGen.Props.PropRotationSettingsEditor.OnInspectorGUI
  id: OnInspectorGUI
  parent: MoraGames.MapGen.Props.PropRotationSettingsEditor
  langs:
  - csharp
  - vb
  name: OnInspectorGUI()
  nameWithType: PropRotationSettingsEditor.OnInspectorGUI()
  fullName: MoraGames.MapGen.Props.PropRotationSettingsEditor.OnInspectorGUI()
  type: Method
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen.Props
  example: []
  syntax:
    content: public override void OnInspectorGUI()
    content.vb: Public Overrides Sub OnInspectorGUI()
  overload: MoraGames.MapGen.Props.PropRotationSettingsEditor.OnInspectorGUI*
- uid: MoraGames.MapGen.Props.PropRotationSettingsEditor.#ctor
  commentId: M:MoraGames.MapGen.Props.PropRotationSettingsEditor.#ctor
  id: '#ctor'
  parent: MoraGames.MapGen.Props.PropRotationSettingsEditor
  langs:
  - csharp
  - vb
  name: PropRotationSettingsEditor()
  nameWithType: PropRotationSettingsEditor.PropRotationSettingsEditor()
  fullName: MoraGames.MapGen.Props.PropRotationSettingsEditor.PropRotationSettingsEditor()
  type: Constructor
  assemblies:
  - MoraMapGen
  namespace: MoraGames.MapGen.Props
  syntax:
    content: public PropRotationSettingsEditor()
    content.vb: Public Sub New()
  overload: MoraGames.MapGen.Props.PropRotationSettingsEditor.#ctor*
  nameWithType.vb: PropRotationSettingsEditor.New()
  fullName.vb: MoraGames.MapGen.Props.PropRotationSettingsEditor.New()
  name.vb: New()
references:
- uid: MoraGames.MapGen.Props
  commentId: N:MoraGames.MapGen.Props
  isExternal: true
  href: MoraGames.html
  name: MoraGames.MapGen.Props
  nameWithType: MoraGames.MapGen.Props
  fullName: MoraGames.MapGen.Props
  spec.csharp:
  - uid: MoraGames
    name: MoraGames
    isExternal: true
    href: MoraGames.html
  - name: .
  - uid: MoraGames.MapGen
    name: MapGen
    isExternal: true
    href: MoraGames.MapGen.html
  - name: .
  - uid: MoraGames.MapGen.Props
    name: Props
    isExternal: true
    href: MoraGames.MapGen.Props.html
  spec.vb:
  - uid: MoraGames
    name: MoraGames
    isExternal: true
    href: MoraGames.html
  - name: .
  - uid: MoraGames.MapGen
    name: MapGen
    isExternal: true
    href: MoraGames.MapGen.html
  - name: .
  - uid: MoraGames.MapGen.Props
    name: Props
    isExternal: true
    href: MoraGames.MapGen.Props.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MoraGames.MapGen.Props.PropRotationSettingsEditor.OnInspectorGUI*
  commentId: Overload:MoraGames.MapGen.Props.PropRotationSettingsEditor.OnInspectorGUI
  isExternal: true
  href: MoraGames.MapGen.Props.PropRotationSettingsEditor.html#MoraGames_MapGen_Props_PropRotationSettingsEditor_OnInspectorGUI
  name: OnInspectorGUI
  nameWithType: PropRotationSettingsEditor.OnInspectorGUI
  fullName: MoraGames.MapGen.Props.PropRotationSettingsEditor.OnInspectorGUI
- uid: MoraGames.MapGen.Props.PropRotationSettingsEditor.#ctor*
  commentId: Overload:MoraGames.MapGen.Props.PropRotationSettingsEditor.#ctor
  isExternal: true
  href: MoraGames.MapGen.Props.PropRotationSettingsEditor.html#MoraGames_MapGen_Props_PropRotationSettingsEditor__ctor
  name: PropRotationSettingsEditor
  nameWithType: PropRotationSettingsEditor.PropRotationSettingsEditor
  fullName: MoraGames.MapGen.Props.PropRotationSettingsEditor.PropRotationSettingsEditor
  nameWithType.vb: PropRotationSettingsEditor.New
  fullName.vb: MoraGames.MapGen.Props.PropRotationSettingsEditor.New
  name.vb: New
